<?php
// uptime:2012-05-03 15:46:05
// ECISP.CN 
$CONFIG=Array(
     //ICP备案
     'icpbeian'=>'',
     //网站状态
     'is_close'=>0,
     //管理员Email
     'admine_mail'=>'zb188@126.com',
     //网站网址
     'domain'=>'http://127.0.0.1/espcms/',
     //日志记录
     'is_log'=>1,
     //时区设置(默认+8)
     'cli_time'=>8,
     //内容生成方式
     'is_html'=>1,
     //生成格式设置
     'file_fileex'=>'html',
     //开启GZip功能
     'is_gzip'=>0,
     //后台默认站点
     'default_lng'=>'cn',
     //HTML生成目录
     'file_htmldir'=>'html/',
     //缓存开启类型
     'is_caching'=>0,
     //缓存更新时间
     'cache_time'=>'3600',
     //链接地址路径方式
     'http_pathtype'=>1,
     //首页生成文件名
     'entrance_file'=>'index',
     //关闭网站说明
     'close_content'=>'抱歉：网站正在维护中，给您带来不便深表歉意！',
     //验证码背景色
     'scode_bgcolor'=>'#B5EBFC',
     //前台默认站点
     'home_lng'=>'cn',
     //伪静态方式
     'is_rewrite'=>0,
     //WAP网站状态
     'is_wap'=>1,
     //验证码干扰码
     'scode_adulterate'=>1,
     //验证码阴影
     'scode_shadow'=>0,
     //验证码字体颜色
     'scode_fontcolor'=>'#818CC1',
     //单语言网站
     'is_alonelng'=>0,
     //网站名称
     'sitename'=>'慈溪大光明电器有限公司',
     //会员登陆验证码
     'mem_isseccode'=>1,
     //会员邮箱验证激活
     'mem_isemail'=>0,
     //Ucenter接口状态
     'mem_isucenter'=>0,
     //Ucenter数据库地址
     'mem_ucdbhost'=>'localhost',
     //Ucenter数据库访问名
     'mem_ucdbuser'=>'root',
     //Ucenter数据库密码
     'mem_ucdbpw'=>'',
     //Ucenter数据库名称
     'mem_ucdbname'=>'ucenter',
     //Ucenter数据库编码
     'mem_ucdbchart'=>'utf8',
     //Ucenter表单前缀
     'mem_ucdbtable'=>'uc_',
     //通信密钥
     'mem_uckey'=>'',
     //UCenter访问地址
     'mem_ucapi'=>'',
     //UCenter系统编码
     'mem_ucchart'=>'utf-8',
     //UCenter应用ID
     'mem_ucapiid'=>0,
     //不允许注册用户名
     'mem_lock'=>'www,bbs,demo,test,ftp,mail,user,users,admin,administrator',
     //会员导航栏显示
     'member_menu'=>1,
     //会员审核类型
     'mem_isclass'=>0,
     //下拉地区选项
     'mem_isaddress'=>1,
     //会员功能状态
     'mem_isclose'=>1,
     //注册条款关联ID
     'mem_did'=>'cn:0,en:0',
     //奖励积分比例
     'order_integral'=>10,
     //商品默认折扣
     'order_discount'=>100,
     //商家公司全称
     'order_companyname'=>'',
     //联系人
     'order_contact'=>'',
     //所处省
     'order_province'=>'',
     //城市
     'order_city'=>'',
     //详细地址
     'order_add'=>'',
     //邮编
     'order_post'=>'',
     //电话
     'order_tel'=>'',
     //手机
     'order_moblie'=>'',
     //订单编号格式字符
     'order_snfont'=>'ESP-',
     //货币种类
     'order_moneytype'=>'￥',
     //订单导航显示方式
     'order_menu'=>1,
     //订单列表显示数
     'order_max_list'=>10,
     //询价权限
     'is_enquiry_memclass'=>0,
     //询价导航显示方式
     'enquiry_menu'=>1,
     //上传文件夹
     'upfile_dir'=>'upfile/',
     //文件大小限制
     'upfile_maxsize'=>'1000000',
     //图片宽
     'img_width'=>200,
     //图片高
     'img_height'=>200,
     //图片背景颜色
     'img_bgcolor'=>'#ffffff',
     //允许上传图片格式
     'upfile_pictype'=>'jpg|png|gif',
     //图片质量
     'img_quality'=>'80',
     //是否生成缩略图
     'img_issmallpic'=>0,
     //允许上传视频格式
     'uifile_movertype'=>'swf|mpg|flv',
     //水印类型
     'img_iswater'=>'0',
     //水印文字
     'img_wmt_text'=>'EasySitePM',
     //水印文字大小
     'img_wmt_size'=>10,
     //水印字体颜色
     'img_wmt_color'=>'#ffffff',
     //水印文字放置位置
     'img_wmt_pos'=>'9',
     //水印文字透明度
     'img_wmt_transparent'=>'20',
     //水印图片文件名
     'img_wmi_file'=>'watermark.png',
     //水印图片放置位置
     'img_wmi_pos'=>'9',
     //水印图片透明度
     'img_wmi_transparent'=>'50',
     //允许上传文件格式
     'upfile_filetype'=>'zip|rar|doc|xls',
     //过滤字组
     'bbs_filter'=>'江泽民|AV|邓小平|毛泽东|SEX',
     //留言审核模式
     'bbs_isclass'=>0,
     //验证码
     'bbs_isseccode'=>0,
     //防刷时间设置
     'bbs_inputtime'=>'0',
     //内容留言列表数量
     'bbs_max_list'=>'15',
     //禁止用户名
     'bbs_username'=>'',
     //留言权限
     'is_anonymous'=>1,
     //内容留言邮件提醒
     'bbs_ismail'=>1,
     //开启邮件发送
     'is_email'=>0,
     //SMTP服务器
     'smtp_server'=>'',
     //SMTP用户名
     'smtp_username'=>'',
     //SMTP密码
     'smtp_password'=>'',
     //内容简介获取
     'input_isdes'=>1,
     //即时通显示类型
     'is_imcall'=>1,
     //删除非站内链接
     'input_isdellink'=>0,
     //内容简介获取长度
     'input_isdescription'=>250,
     //默认点击数
     'input_click'=>0,
     //内链接启用方式
     'is_keylink'=>0,
     //标题默认颜色
     'input_color'=>'#000000',
     //即时通外观样式
     'call_style'=>'1',
     //即时通显示方式
     'call_type'=>'1',
     //即时通显示位置
     'call_position'=>'2',
     //邮件发送方式
     'smtp_type'=>'2',
     //邮件头的分隔符
     'mail_cat'=>'1',
     //SMTP服务器端口
     'smtp_port'=>'25',
     //发送邮箱
     'mail_send'=>'',
     //后台翻页按钮数量
     'max_page'=>5,
     //后台每页内容数量
     'max_list'=>20,
     //产品上传图片数量
     'upfile_maxalbum'=>3,
     //SEO生成文件目录
     'file_sitemapdir'=>'sitemap/',
     //sql备份文件目录
     'file_sqlbakdir'=>'datacache/backup/',
     //当前模板
     'default_templates'=>'default',
     //模板文件扩展名
     'templates_fileex'=>'html',
     //内容关键字获取
     'input_iskey'=>0,
     //默认物流方式
     'order_shipping'=>1,
     //默认支付方式
     'order_pay'=>1,
     //会员积分策略
     'mem_isintegral'=>1,
     //关键字获取数量
     'input_iskeyword'=>10,
     //默认编辑
     'input_author'=>'轻舞飞沙',
     //默认来源
     'input_source'=>'Ecisp.CN',
     //热门点击数量
     'input_hot'=>100,
     //发布内容即时生成方式
     'is_inputhtml'=>1,
     //继续发布控制
     'is_inputclose'=>1,
     //codefile
     'cer_file'=>'',
     //key
     'cer_key'=>'',
     //cn默认代码
     'is_lancode'=>'cn',
)
?>